### ISSUE TITLE
exporting text to png does not use transparent background

### ISSUE THREAD

**Issue by monological** [GeertWille/sketch-to-xcode-assets-catalog#12]
When exporting a text layer, the background is set to black instead of using a transparent background. If I export the layer directly through the app, the background is transparent.

**Comment by GeertWille** [comment]
Can you link to an example sketch file please?

**Comment by alexlr** [comment]
Do you have a background color set for your artboard? And if so, is it checked to include during export? Ran into the same problem and that was the issue.

**Comment by GeertWille** [comment]
Fixed with new update...
