### ISSUE TITLE
Exporting any BG color on canvas / transparency being trimmed.

### ISSUE THREAD

**Issue by sophiamf** [GeertWille/sketch-to-xcode-assets-catalog#21]
Turned off canvas BG color on inspector. 
Hid color layer on BG.

Successfully export on blank canvas but lost transparent padding.

**Comment by GeertWille** [comment]
Please read the section "Adding Padding to slices" in [README](https://github.com/GeertWille/sketch-to-xcode-assets-catalog/blob/master/README.md). This should fix your issue...

**Comment by sophiamf** [comment]
<img width="344" alt="screen shot 2016-01-06 at 6 34 27 pm" src="https://cloud.githubusercontent.com/assets/10751578/12158006/2ca5ac14-b4a4-11e5-99f7-3b652de08101.png">
The slice layer is not working.The right is whats export. The left is the slice layer.
