### ISSUE TITLE
Jpeg format is irrelevant

### ISSUE THREAD

**Issue by kjelleve** [GeertWille/sketch-to-xcode-assets-catalog#5]
Xcode assets library only works with png format, so all exported images should be PNG. (The leading 'p_' & 'j_' are irrelevant and should be removed)

**Comment by Flying-Osterich** [comment]
It is helpful to have the iTunesArtwork@2x in jpeg format.

**Comment by GeertWille** [comment]
I'll keep the support for jpeg format for now
