### ISSUE TITLE
Export produces blank files

### ISSUE THREAD

**Issue by fwaddle** [GeertWille/sketch-to-xcode-assets-catalog#7]
I've tried changing the name of the layer to go through all the different options p_t__, j_u__, etc. but when I export I get 3 blank files.
The json file as well as the png's/jpg's get created but when I open them, they're blank. I.e. the png's are fully transparent with no image while the jpg's are just plain white.

What am I doing wrong here?

Update: Ok so it looks like I was attempting to export a slice instead of the shapes themselves. So I assume with this plugin, we don't use slices?

**Comment by GeertWille** [comment]
That's right.. You don't need to use slices. :)
