### ISSUE TITLE
fitletype:pdf export for Xcode?

### ISSUE THREAD

**Issue by ryh** [GeertWille/sketch-to-xcode-assets-catalog#9]
I tried to add this

``` js
else if (fileType == "v_") {
            imageExtension = ".pdf";
        }
```

it worked, but can't find  `@2x` `@3x` file generate code ( 1x is enough :smile: )

**Comment by markiv** [comment]
Please reconsider adding PDF export support.

**Comment by GeertWille** [comment]
Can you describe a little bit more in depth what you exactly mean?

Op vr 13 nov. 2015 11:18 schreef Vikram Kriplaney <notifications@github.com

**Comment by ryh** [comment]
Xcode now can use `vector PDF` as image, that is no more need `@2x` `@3x` for the vector image file `.pdf` , and it may be best practice for Images Use in iOS
